version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /buildboxes/alpine
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /buildboxes/ubuntu
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
