# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                  = "nwlabs-381491855445-iac-state"
    dynamodb_table          = "nwlabs-381491855445-iac-locks"
    encrypt                 = true
    key                     = "package-building/s3/iac.tfstate"
    region                  = "us-east-2"
    skip_metadata_api_check = true
  }
}
